import type { Task } from "@/types/task"

export const mockTasks: Task[] = [
  {
    _id: "task-1",
    title: "Create Login UI",
    description: "Implement login page with form validation, password visibility toggle, remember me, and forgot password link. Use React Hook Form + Zod. Responsive design required.",
    project: "1",
    assignee: "mock-dev-1",
    createdBy: "mock-admin-1",
    status: "DONE",
    priority: "HIGH",
    labels: ["Frontend", "Auth", "UI"],
    dueDate: "2024-09-28",
    attachments: [],
    comments: [],
    createdAt: "2024-09-20T10:00:00Z",
    updatedAt: "2024-09-28T15:00:00Z",
  },
  {
    _id: "task-2",
    title: "Create Register API",
    description: "Build POST /api/auth/register endpoint with validation, password hashing with bcrypt, JWT generation, and duplicate email check. Use NestJS DTOs.",
    project: "1",
    assignee: "mock-manager-1",
    createdBy: "mock-admin-1",
    status: "IN_REVIEW",
    priority: "HIGH",
    labels: ["Backend", "API", "Auth"],
    dueDate: "2024-09-30",
    attachments: [],
    comments: [],
    createdAt: "2024-09-21T09:00:00Z",
    updatedAt: "2024-09-30T10:00:00Z",
  },
  {
    _id: "task-3",
    title: "Create Book API",
    description: "Implement CRUD for books: GET /books with search, filter, pagination, GET /books/:id, POST /books, PUT /books/:id, DELETE /books/:id. Include cover image upload.",
    project: "1",
    assignee: "user-2",
    createdBy: "mock-manager-1",
    status: "IN_PROGRESS",
    priority: "URGENT",
    labels: ["Backend", "API", "Feature"],
    dueDate: "2024-10-02",
    attachments: [],
    comments: [],
    createdAt: "2024-09-22T11:00:00Z",
    updatedAt: "2024-09-24T14:00:00Z",
  },
  {
    _id: "task-4",
    title: "Create Search UI",
    description: "Build book search page with debounced input, filters for category, price, rating, sort options, and grid/list view toggle. Use useDebounce hook.",
    project: "1",
    assignee: "user-3",
    createdBy: "mock-manager-1",
    status: "TODO",
    priority: "MEDIUM",
    labels: ["Frontend", "UI", "Search"],
    dueDate: "2024-10-05",
    attachments: [],
    comments: [],
    createdAt: "2024-09-23T10:00:00Z",
    updatedAt: "2024-09-23T10:00:00Z",
  },
  {
    _id: "task-5",
    title: "Create Cart",
    description: "Implement shopping cart with add/remove, quantity update, total calculation, persist in localStorage, and sync with backend.",
    project: "1",
    assignee: "user-4",
    createdBy: "mock-manager-1",
    status: "TODO",
    priority: "HIGH",
    labels: ["Frontend", "Feature"],
    dueDate: "2024-10-08",
    attachments: [],
    comments: [],
    createdAt: "2024-09-23T12:00:00Z",
    updatedAt: "2024-09-23T12:00:00Z",
  },
  {
    _id: "task-6",
    title: "Create Payment Integration",
    description: "Integrate Stripe for payments: checkout session, webhooks for payment success/failure, receipt generation, and order creation after payment.",
    project: "1",
    assignee: "mock-dev-1",
    createdBy: "mock-admin-1",
    status: "IN_PROGRESS",
    priority: "URGENT",
    labels: ["Backend", "Payment", "API"],
    dueDate: "2024-10-01",
    attachments: [],
    comments: [],
    createdAt: "2024-09-20T14:00:00Z",
    updatedAt: "2024-09-25T09:00:00Z",
  },
  {
    _id: "task-7",
    title: "Navbar Responsive",
    description: "Build responsive navbar with mobile drawer, search, notifications dropdown, user menu, and active link highlighting.",
    project: "6",
    assignee: "user-2",
    createdBy: "mock-admin-1",
    status: "DONE",
    priority: "LOW",
    labels: ["Frontend", "UI"],
    dueDate: "2024-09-25",
    attachments: [],
    comments: [],
    createdAt: "2024-09-20T08:00:00Z",
    updatedAt: "2024-09-25T10:00:00Z",
  },
  {
    _id: "task-8",
    title: "Footer Component",
    description: "Create footer with links, social icons, newsletter signup, and responsive layout.",
    project: "6",
    assignee: "user-3",
    createdBy: "mock-admin-1",
    status: "DONE",
    priority: "LOW",
    labels: ["Frontend", "UI"],
    dueDate: "2024-09-26",
    attachments: [],
    comments: [],
    createdAt: "2024-09-21T08:00:00Z",
    updatedAt: "2024-09-26T11:00:00Z",
  },
  {
    _id: "task-9",
    title: "Dashboard Analytics",
    description: "Implement dashboard with stats cards, Recharts for task distribution, project progress, tasks over time, and recent activity.",
    project: "6",
    assignee: "mock-admin-1",
    createdBy: "mock-admin-1",
    status: "IN_REVIEW",
    priority: "MEDIUM",
    labels: ["Frontend", "Feature"],
    dueDate: "2024-09-30",
    attachments: [],
    comments: [],
    createdAt: "2024-09-22T09:00:00Z",
    updatedAt: "2024-09-30T12:00:00Z",
  },
  {
    _id: "task-10",
    title: "Project CRUD APIs",
    description: "Build NestJS modules for projects: CRUD endpoints, validation with class-validator, role guards, and Swagger docs.",
    project: "6",
    assignee: "mock-manager-1",
    createdBy: "mock-admin-1",
    status: "TODO",
    priority: "HIGH",
    labels: ["Backend", "API"],
    dueDate: "2024-10-03",
    attachments: [],
    comments: [],
    createdAt: "2024-09-24T10:00:00Z",
    updatedAt: "2024-09-24T10:00:00Z",
  },
  {
    _id: "task-11",
    title: "Product Page UI",
    description: "Build product detail page with image gallery, reviews, related products, add to cart, and wishlist.",
    project: "2",
    assignee: "user-4",
    createdBy: "mock-manager-1",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    labels: ["Frontend", "UI"],
    dueDate: "2024-10-04",
    attachments: [],
    comments: [],
    createdAt: "2024-09-24T11:00:00Z",
    updatedAt: "2024-09-24T16:00:00Z",
  },
  {
    _id: "task-12",
    title: "Fix Login Bug",
    description: "Fix bug where login fails when password has special characters. Investigate bcrypt compare and update validation.",
    project: "1",
    assignee: "user-5",
    createdBy: "mock-dev-1",
    status: "TODO",
    priority: "URGENT",
    labels: ["Bug", "Auth", "Backend"],
    dueDate: "2024-09-27",
    attachments: [],
    comments: [],
    createdAt: "2024-09-25T08:00:00Z",
    updatedAt: "2024-09-25T08:00:00Z",
  },
]

export const mockComments = [
  {
    _id: "comment-1",
    task: "task-3",
    user: { _id: "mock-admin-1", name: "Ronak Patel", avatar: "R" },
    content: "Payment API integration is ready for review. Added Stripe webhooks and receipt generation.",
    createdAt: "2024-09-24T14:30:00Z",
    updatedAt: "2024-09-24T14:30:00Z",
  },
  {
    _id: "comment-2",
    task: "task-3",
    user: { _id: "mock-dev-1", name: "Amit Kumar", avatar: "A" },
    content: "I'll integrate the frontend today. Need the API docs for checkout session.",
    createdAt: "2024-09-24T15:00:00Z",
    updatedAt: "2024-09-24T15:00:00Z",
  },
  {
    _id: "comment-3",
    task: "task-6",
    user: { _id: "user-2", name: "Priya Singh", avatar: "P" },
    content: "Search UI is 80% done. Need to add filters for price and rating.",
    createdAt: "2024-09-23T16:00:00Z",
    updatedAt: "2024-09-23T16:00:00Z",
  },
]
