import type { Project } from "@/types/project"

export const mockProjects: Project[] = [
  {
    _id: "1",
    name: "Book Marketplace",
    description: "Build an online book marketplace with search, cart, wishlist, and Stripe payments. Includes admin dashboard and analytics.",
    status: "ACTIVE",
    priority: "HIGH",
    startDate: "2024-09-01",
    dueDate: "2024-12-31",
    owner: "mock-admin-1",
    members: ["mock-admin-1", "mock-manager-1", "mock-dev-1", "user-2", "user-3", "user-4", "user-5", "user-6"],
    progress: 72,
    tasksCount: 20,
    completedTasks: 12,
    createdAt: "2024-09-01T10:00:00Z",
    updatedAt: "2024-09-24T10:00:00Z",
  },
  {
    _id: "2",
    name: "E-Commerce Mobile App",
    description: "Cross-platform mobile shopping experience with React Native. Features include barcode scanning, AR try-on, and offline support.",
    status: "ACTIVE",
    priority: "URGENT",
    startDate: "2024-08-15",
    dueDate: "2024-11-30",
    owner: "mock-manager-1",
    members: ["mock-manager-1", "user-2", "user-3", "user-4", "user-5"],
    progress: 45,
    tasksCount: 32,
    completedTasks: 14,
    createdAt: "2024-08-15T09:00:00Z",
    updatedAt: "2024-09-23T15:00:00Z",
  },
  {
    _id: "3",
    name: "Analytics Dashboard",
    description: "Real-time analytics for business metrics with Recharts, data export, and custom report builder.",
    status: "ACTIVE",
    priority: "MEDIUM",
    startDate: "2024-09-10",
    dueDate: "2024-10-31",
    owner: "mock-admin-1",
    members: ["mock-admin-1", "user-3", "user-4", "user-6"],
    progress: 90,
    tasksCount: 15,
    completedTasks: 13,
    createdAt: "2024-09-10T11:00:00Z",
    updatedAt: "2024-09-24T08:00:00Z",
  },
  {
    _id: "4",
    name: "Mobile Banking App",
    description: "Secure banking app with biometric auth, transaction history, bill payments, and budgeting tools.",
    status: "PLANNING",
    priority: "HIGH",
    startDate: "2024-10-01",
    dueDate: "2025-02-28",
    owner: "mock-manager-1",
    members: ["mock-manager-1", "user-2", "user-5"],
    progress: 15,
    tasksCount: 28,
    completedTasks: 4,
    createdAt: "2024-09-20T14:00:00Z",
    updatedAt: "2024-09-22T10:00:00Z",
  },
  {
    _id: "5",
    name: "AI Content Generator",
    description: "AI-powered content generation tool with GPT integration, template library, and team collaboration.",
    status: "ON_HOLD",
    priority: "LOW",
    startDate: "2024-07-01",
    dueDate: "2024-09-30",
    owner: "mock-admin-1",
    members: ["mock-admin-1", "user-4"],
    progress: 60,
    tasksCount: 18,
    completedTasks: 10,
    createdAt: "2024-07-01T10:00:00Z",
    updatedAt: "2024-09-15T12:00:00Z",
  },
  {
    _id: "6",
    name: "DevFlow Platform",
    description: "The current project - developer collaboration and project management platform. Meta project for building itself.",
    status: "ACTIVE",
    priority: "URGENT",
    startDate: "2024-09-20",
    dueDate: "2024-12-15",
    owner: "mock-admin-1",
    members: ["mock-admin-1", "mock-manager-1", "mock-dev-1"],
    progress: 35,
    tasksCount: 45,
    completedTasks: 15,
    createdAt: "2024-09-20T08:00:00Z",
    updatedAt: "2024-09-25T08:00:00Z",
  },
]

export const mockUsersForProjects = [
  { _id: "mock-admin-1", name: "Ronak Patel", email: "admin@devflow.com", avatar: "R" },
  { _id: "mock-manager-1", name: "Rahul Sharma", email: "manager@devflow.com", avatar: "R" },
  { _id: "mock-dev-1", name: "Amit Kumar", email: "developer@devflow.com", avatar: "A" },
  { _id: "user-2", name: "Priya Singh", email: "priya@devflow.com", avatar: "P" },
  { _id: "user-3", name: "Neha Gupta", email: "neha@devflow.com", avatar: "N" },
  { _id: "user-4", name: "Vikram Patel", email: "vikram@devflow.com", avatar: "V" },
  { _id: "user-5", name: "Sneha Reddy", email: "sneha@devflow.com", avatar: "S" },
  { _id: "user-6", name: "Arjun Mehta", email: "arjun@devflow.com", avatar: "A" },
]
